-- ============================================================
--  Blipwork — cut `crystal-orbit`   (2026-08-08)
-- ------------------------------------------------------------
--  Megan's call on seeing it worn: "remove crystal orbit, it looks dumb."
--  Same kind of decision as shadow-crown (wave 2) and pearls/gold-chain
--  (the neck wave) — assertions prove structure, only looking proves art.
--
--  A PLAIN DELETE is safe because the app is still with no learner, so
--  nobody can own or have equipped it. Once kids are on it, retire with
--  `update public.shop_items set active = false ...` instead, so the item
--  leaves the shop without being confiscated from anyone's closet.
--
--  migration-effects-slot.sql, which seeded it, is deliberately left
--  untouched — an applied migration records what actually ran. The removal
--  lives here, in the newer file, and verify-store.html reads deletes out
--  of every migration to enforce that a cut id never reappears in the
--  client mirror.
--
--  The effects slot keeps light-ring (free, L1), flame-ring and spark-halo
--  — still two or more items and still a free level-1 one, which is what
--  verify-store.html requires of every slot.
--
--  Also removed from: js/companion/renderer.js, js/companion/blip-ui.js,
--  js/companion/collections.js, js/local-backend.js, supabase/schema.sql,
--  and the "Monarch" outfit in verify-store.html. The PNG stays on disk
--  for now; it is referenced by nothing.
-- ============================================================

delete from public.shop_items where item_id = 'crystal-orbit';
